[tools.isort]
py_version = 310
profile = 'django'
line_length = 120
multi_line_output = 2
known_first_party = ["todolist", "core"]

[tool.flake8]
max-line-length = 120
per-file-ignores = """
   venv
"""
