version: '3.9'

services:

  postgres:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3


  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


  api:
    image: pablit71/graduate_work:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pg_data_todolist: