# Generated by Django 4.1.3 on 2022-11-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_tg',
            field=models.IntegerField(null=True),
        ),
    ]
