# Generated by Django 4.1.3 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_id_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_tg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
