# Generated by Django 4.1.3 on 2022-11-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_id_tg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_tg',
            new_name='verification_code',
        ),
    ]
